# Generated by Django 4.1.4 on 2022-12-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filiere", models.CharField(max_length=255)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("S1", "Semester1"),
                            ("S2", "Semester2"),
                            ("S3", "Semester3"),
                            ("S4", "Semester4"),
                            ("S5", "Semester5"),
                            ("S6", "Semester6"),
                        ],
                        default="S1",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
            ],
        ),
    ]
