# Generated by Django 4.1.4 on 2022-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiveapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archive",
            name="file_size",
        ),
        migrations.AddField(
            model_name="archive",
            name="file",
            field=models.FileField(default=1, upload_to="files/"),
            preserve_default=False,
        ),
    ]
