# Generated by Django 4.1.5 on 2023-01-24 09:54

import archiveapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiveapp", "0003_remove_archive_file_archive_files_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archive",
            name="files",
        ),
        migrations.AddField(
            model_name="archive",
            name="file",
            field=archiveapp.models.CustomFileField(blank=True, upload_to="files/"),
        ),
    ]
